name: CI

on:
  pull_request: {}
  push:
    branches:
      - "main"
    tags:
      - "v*"

jobs:
  test:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: "go.mod"
          cache: true
          check-latest: true

      - run: "go test -v -cover -count 1 ./..."

  lint:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: "go.mod"
          cache: true
          check-latest: true

      - uses: golangci/golangci-lint-action@v3
