name: Package

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  package-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Unshallow
        run: git fetch --prune --unshallow
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: "go.mod"
          cache: true
          check-latest: true
      - name: Build Executable (windows)
        run: |
          go build -o ./com.paultyng.slack.sdPlugin/
      - name: Build Executable (darwin)
        env:
          GOOS: darwin
          GOARCH: amd64 # arm?
        run: |
          go build -o ./com.paultyng.slack.sdPlugin/
      - name: Set Version
        run: |
          mv ./com.paultyng.slack.sdPlugin/manifest.json ./manifest.json
          $version = git describe --tags
          $version = $version.Trim("v")
          Write-Output $version
          jq ".Version=\`"$version\`"" ./manifest.json > ./com.paultyng.slack.sdPlugin/manifest.json
      - name: Package Plugin
        run: |
          mkdir -p ./dist/
          jq . ./com.paultyng.slack.sdPlugin/manifest.json
          ./tools/DistributionTool.exe -b -i ./com.paultyng.slack.sdPlugin -o ./dist/
      - name: Upload Asset
        uses: softprops/action-gh-release@v1
        with:
          files: dist/com.paultyng.slack.sdPlugin.streamDeckPlugin
